"""
Regenerate the auto-managed 'Current Known Issues' block of brain/CLAUDE.md
from output/analysis/latest_alerts.json.

Idempotent: writes only if content changed. Wired into db_sync.py main() so
every sync refreshes the snapshot. Can also be invoked directly:

    python update_claude_md.py

Boundary contract:
    Anything between
        <!-- AUTO:CURRENT_KNOWN_ISSUES START -->
        <!-- AUTO:CURRENT_KNOWN_ISSUES END -->
    is OWNED by this script and overwritten on every run. Hand-edits in that
    region will be lost. Put narrative analysis in
    knowledge/investigation_context.md (different decay rate, not auto-managed).

If the markers are missing on first run we INSERT them, replacing whatever
existing '## Current Known Issues' heading we can find. After that, the
markers are the only anchor used.
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

BRAIN_DIR = Path(__file__).resolve().parent
CLAUDE_MD = BRAIN_DIR / 'CLAUDE.md'
ALERTS_JSON = BRAIN_DIR / 'analysis' / 'latest_alerts.json'

START_MARK = '<!-- AUTO:CURRENT_KNOWN_ISSUES START -->'
END_MARK = '<!-- AUTO:CURRENT_KNOWN_ISSUES END -->'


def _fmt_age(hours: float) -> str:
    days = hours / 24
    if days >= 2:
        return f"{hours:.1f}h ({days:.1f} days)"
    return f"{hours:.1f}h"


def render_section(data: dict) -> str:
    """Return the full marker-wrapped block, including START/END markers."""
    lines: list[str] = [START_MARK, '']
    lines.append('## Current Known Issues (auto-generated)')
    lines.append('')

    check_time = data.get('check_time', 'unknown')
    lines.append(
        f"_Source: `output/analysis/latest_alerts.json` (check_time `{check_time}`). "
        f"Regenerated by `brain/update_claude_md.py` on every sync. "
        f"Hand-edits here will be overwritten — put narrative analysis in "
        f"`knowledge/investigation_context.md` instead._"
    )
    lines.append('')

    overall = data.get('status', 'UNKNOWN')
    lines.append(f"**Overall status:** `{overall}`")
    lines.append('')

    # Staleness (pipeline-level meta alert)
    staleness = data.get('staleness') or {}
    if staleness.get('is_stale'):
        age_str = _fmt_age(staleness.get('age_hours') or 0)
        latest = staleness.get('latest_reading', 'unknown')
        threshold_h = staleness.get('threshold_hours', 0)
        lines.append(
            f"**🔴 Pipeline STALE:** newest reading is {age_str} old "
            f"(`{latest}`). Threshold {threshold_h}h. "
            f"All alerts below describe state at that timestamp, **not live state**."
        )
        lines.append('')
    elif staleness.get('age_hours') is not None:
        age_str = _fmt_age(staleness['age_hours'])
        lines.append(f"_Pipeline freshness OK — latest reading {age_str} old._")
        lines.append('')

    # Per-sensor alerts
    alerts = data.get('alerts') or []
    if alerts:
        lines.append(f"### Active alerts ({len(alerts)})")
        lines.append('')
        lines.append('| Pool | Sensor | Level | Value | Normal | Sustained |')
        lines.append('|------|--------|-------|-------|--------|-----------|')
        # Order: CRITICAL first, then by pool/sensor for stability
        ordered = sorted(
            alerts,
            key=lambda a: (0 if a.get('level') == 'CRITICAL' else 1,
                           a.get('pool', ''), a.get('sensor', '')),
        )
        for a in ordered:
            level = a.get('level', '?')
            icon = '🔴' if level == 'CRITICAL' else '⚠️'
            lines.append(
                f"| {a.get('pool', '?')} | {a.get('sensor', '?')} | "
                f"{icon} {level} | {a.get('current_value', '?')} | "
                f"{a.get('normal_range', '?')} | "
                f"{a.get('sustained_readings', 0)} readings |"
            )
        lines.append('')
    else:
        lines.append('### Active alerts')
        lines.append('')
        lines.append('_None._')
        lines.append('')

    # Trends
    trends = data.get('trends') or []
    if trends:
        lines.append(f"### Trends ({len(trends)})")
        lines.append('')
        for t in trends:
            arrow = '↗' if t.get('direction') == 'RISING' else '↘'
            lines.append(
                f"- **{t.get('pool', '?')} {t.get('sensor', '?')}** {arrow} "
                f"{(t.get('direction') or '').lower()} for {t.get('days', '?')} days "
                f"(Δ {t.get('total_change', 0):+.3f})"
            )
        lines.append('')

    lines.append(END_MARK)
    return '\n'.join(lines)


# Pattern that matches an EXISTING auto-block (across newlines). Markers are
# unique strings so we don't need anchor heuristics — re.DOTALL on the body.
_BLOCK_RE = re.compile(
    re.escape(START_MARK) + r'.*?' + re.escape(END_MARK),
    re.DOTALL,
)

# Fallback (first-run only): match a hand-written 'Current Known Issues'
# section from its heading down to the next h2 heading or end of file. The
# replacement will install the markers in place of this section.
_LEGACY_SECTION_RE = re.compile(
    r'^## Current Known Issues.*?(?=^## |\Z)',
    re.MULTILINE | re.DOTALL,
)


def _replace_or_insert(current: str, new_block: str) -> str:
    if _BLOCK_RE.search(current):
        return _BLOCK_RE.sub(new_block, current, count=1)
    if _LEGACY_SECTION_RE.search(current):
        # On first run: replace the legacy hand-written section with the
        # marked auto-block. Future runs hit the BLOCK_RE branch above.
        return _LEGACY_SECTION_RE.sub(new_block + '\n\n', current, count=1)
    # Last resort: append at end of file.
    return current.rstrip() + '\n\n' + new_block + '\n'


def update(verbose: bool = True) -> bool:
    """Return True iff CLAUDE.md was rewritten."""
    if not ALERTS_JSON.exists():
        if verbose:
            print(f"no alerts file at {ALERTS_JSON}; skipping CLAUDE.md update")
        return False
    if not CLAUDE_MD.exists():
        if verbose:
            print(f"no CLAUDE.md at {CLAUDE_MD}; skipping")
        return False

    try:
        data = json.loads(ALERTS_JSON.read_text(encoding='utf-8'))
    except Exception as e:
        if verbose:
            print(f"could not parse {ALERTS_JSON}: {e}")
        return False

    new_block = render_section(data)
    current = CLAUDE_MD.read_text(encoding='utf-8')
    updated = _replace_or_insert(current, new_block)

    if updated == current:
        if verbose:
            print("CLAUDE.md unchanged")
        return False

    CLAUDE_MD.write_text(updated, encoding='utf-8')
    if verbose:
        print(f"updated {CLAUDE_MD.name}")
    return True


if __name__ == '__main__':
    changed = update()
    sys.exit(0 if changed or True else 1)  # never fail the parent pipeline
