#!/usr/bin/env python3
"""
Build + sign + publish a PoolAIssistant Pi update in one command.

Usage:
    python publish_update.py \\
        --source-dir /path/to/PoolDash_v6 \\
        --signing-key /path/to/update_signing_key \\
        [--description "Release notes ~1 line"]

Reads the version from <source-dir>/VERSION. Builds a tarball. Signs it
with the Ed25519 private key. FTP-uploads tarball + signature + a one-shot
PHP installer that copies both into the admin backend's /data/updates/
directory and upserts software_updates with the checksum + signature
fingerprint. The installer self-deletes on success.

Env vars required (never in repo):
    POOLAI_FTP_HOST, POOLAI_FTP_USER, POOLAI_FTP_PASS

Skip --signing-key to publish unsigned (permissive mode on Pis still
works, with a logged warning). Production should always sign.
"""

from __future__ import annotations

import argparse
import base64
import ftplib
import hashlib
import io
import os
import ssl
import subprocess
import sys
import urllib.request
from pathlib import Path


def fatal(msg: str) -> "None":
    sys.stderr.write(f"[FATAL] {msg}\n")
    sys.exit(1)


def build_tarball(source_dir: Path, version: str, out_path: Path) -> None:
    if not (source_dir / "VERSION").is_file():
        fatal(f"no VERSION file in {source_dir}")

    # Keep exclusions in sync with pi-software/CLAUDE.md's deploy instructions.
    excludes = [
        "--exclude=__pycache__", "--exclude=*.pyc", "--exclude=instance",
        "--exclude=.git", "--exclude=*.sqlite3", "--exclude=docs",
        "--exclude=*.tar.gz", "--exclude=*.sig",
    ]
    cmd = ["tar", "-czf", str(out_path), *excludes, "-C", str(source_dir), "."]
    print(f"[..] Building {out_path.name} from {source_dir}")
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        fatal(f"tar failed: {res.stderr.strip()}")
    print(f"[OK] Tarball ready: {out_path} ({out_path.stat().st_size} bytes)")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def sign_tarball(tarball: Path, key_path: Path) -> Path:
    try:
        from cryptography.hazmat.primitives.serialization import load_ssh_private_key
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    except ImportError:
        fatal("cryptography missing: pip install cryptography")

    try:
        priv = load_ssh_private_key(key_path.read_bytes(), password=None)
    except Exception as e:
        fatal(f"cannot load signing key {key_path}: {e} (is it encrypted? ssh-keygen -p -N '' -f key)")
    if not isinstance(priv, Ed25519PrivateKey):
        fatal("signing key is not Ed25519")

    sig = priv.sign(tarball.read_bytes())
    out = Path(str(tarball) + ".sig")
    out.write_bytes(sig)
    print(f"[OK] Wrote signature {out.name} ({len(sig)} bytes)")
    return out


def ed25519_pub_fingerprint(priv_key_path: Path) -> str:
    """SHA256 fingerprint of the public key matching the private key.
    Displayed in admin UI so operators can confirm which key signed what."""
    try:
        from cryptography.hazmat.primitives.serialization import load_ssh_private_key, Encoding, PublicFormat
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    except ImportError:
        return "unknown"
    try:
        priv = load_ssh_private_key(priv_key_path.read_bytes(), password=None)
    except Exception:
        return "unknown"
    if not isinstance(priv, Ed25519PrivateKey):
        return "unknown"
    pub_bytes = priv.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)
    return "SHA256:" + base64.b64encode(hashlib.sha256(pub_bytes).digest()).decode().rstrip("=")


def ftp_connect() -> ftplib.FTP_TLS:
    host = os.environ["POOLAI_FTP_HOST"]
    user = os.environ["POOLAI_FTP_USER"]
    pw = os.environ["POOLAI_FTP_PASS"]
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    ftp = ftplib.FTP_TLS(host, user, pw, context=ctx, timeout=120)
    ftp.prot_p()
    return ftp


def ftp_put(ftp: ftplib.FTP_TLS, local: Path, remote_name: str) -> None:
    with local.open("rb") as f:
        ftp.storbinary(f"STOR {remote_name}", f)
    print(f"[OK] FTP uploaded {remote_name} ({local.stat().st_size} bytes)")


INSTALLER_TEMPLATE = r"""<?php
/**
 * Generated by publish_update.py - installs v__VERSION__ into the admin
 * backend /data/updates/ and registers in software_updates. Self-deletes.
 */
error_reporting(E_ALL); ini_set('display_errors', 1);
header('Content-Type: text/plain; charset=utf-8');

$version = '__VERSION__';
$checksum = '__CHECKSUM__';
$description = '__DESCRIPTION__';
$sigFingerprint = '__SIG_FPR__';
$filename = "update-v{$version}.tar.gz";
$sigFilename = $filename . '.sig';

$adminBase = '/home/u931726538/domains/modprojects.co.uk/public_html/poolaissistant';
$destDir = $adminBase . '/data/updates/';
if (!is_dir($destDir) && !mkdir($destDir, 0755, true)) {
    die("[ERROR] cannot create $destDir\n");
}

foreach ([$filename, $sigFilename] as $f) {
    $src = __DIR__ . '/' . $f;
    if (!file_exists($src)) {
        if ($f === $sigFilename) { echo "[SKIP] no signature file uploaded (unsigned release)\n"; continue; }
        die("[ERROR] $f not found at FTP root\n");
    }
    $dst = $destDir . $f;
    if (!copy($src, $dst)) die("[ERROR] copy failed $f\n");
    @unlink($src);
    echo "[OK] Staged $f (" . filesize($dst) . " bytes)\n";
}

$tarDst = $destDir . $filename;
$actual = hash_file('sha256', $tarDst);
if (!hash_equals($checksum, $actual)) {
    die("[ERROR] tarball checksum mismatch: wanted $checksum got $actual\n");
}
echo "[OK] Checksum verified\n";

require_once $adminBase . '/config/database.php';
$pdo = db();

$hasSig = file_exists($destDir . $sigFilename);
$sigB64 = $hasSig ? base64_encode(file_get_contents($destDir . $sigFilename)) : null;
$signedAt = $hasSig ? date('Y-m-d H:i:s') : null;

// Insert/upsert row with signature columns (present after schema_update_signatures.sql).
try {
    $pdo->prepare("INSERT INTO software_updates
        (version, filename, file_size, checksum, description, is_active, created_at,
         signature_b64, signature_key_fpr, signed_at)
        VALUES (?, ?, ?, ?, ?, 1, NOW(), ?, ?, ?)
        ON DUPLICATE KEY UPDATE
            filename = VALUES(filename),
            file_size = VALUES(file_size),
            checksum = VALUES(checksum),
            description = VALUES(description),
            is_active = 1,
            signature_b64 = VALUES(signature_b64),
            signature_key_fpr = VALUES(signature_key_fpr),
            signed_at = VALUES(signed_at)
    ")->execute([$version, $filename, filesize($tarDst), $checksum, $description,
                 $sigB64, $hasSig ? $sigFingerprint : null, $signedAt]);
} catch (PDOException $e) {
    // If signature columns haven't been migrated yet, fall back to the legacy insert.
    $pdo->prepare("INSERT INTO software_updates
        (version, filename, file_size, checksum, description, is_active, created_at)
        VALUES (?, ?, ?, ?, ?, 1, NOW())
        ON DUPLICATE KEY UPDATE
            filename = VALUES(filename),
            file_size = VALUES(file_size),
            checksum = VALUES(checksum),
            description = VALUES(description),
            is_active = 1
    ")->execute([$version, $filename, filesize($tarDst), $checksum, $description]);
    echo "[WARN] signature columns missing; signature not recorded in DB (file still in /data/updates/).\n";
}

echo "[OK] software_updates row upserted for v$version\n";
echo (!$hasSig ? "[WARN] Published WITHOUT a signature (permissive-mode Pis will install with a warning).\n" : "");
@unlink(__FILE__);
echo "[OK] Installer self-deleted\n";
"""


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--source-dir", type=Path, required=True,
                   help="PoolDash_v6 directory to tar")
    p.add_argument("--signing-key", type=Path, default=None,
                   help="Ed25519 private key path (omit = unsigned)")
    p.add_argument("--description", default="",
                   help="short release description for admin UI")
    p.add_argument("--poolai-url", default="https://poolai.modprojects.co.uk",
                   help="where to curl the installer")
    p.add_argument("--work-dir", type=Path, default=Path("/tmp"),
                   help="directory for transient build artifacts")
    args = p.parse_args()

    for env_var in ("POOLAI_FTP_HOST", "POOLAI_FTP_USER", "POOLAI_FTP_PASS"):
        if not os.environ.get(env_var):
            fatal(f"env var missing: {env_var}")

    version = (args.source_dir / "VERSION").read_text().strip()
    if not version:
        fatal("VERSION file is empty")

    args.work_dir.mkdir(parents=True, exist_ok=True)
    tarball = args.work_dir / f"update-v{version}.tar.gz"

    build_tarball(args.source_dir, version, tarball)
    checksum = sha256_file(tarball)
    print(f"[OK] SHA256 = {checksum}")

    sig_path = None
    sig_fpr = ""
    if args.signing_key:
        sig_path = sign_tarball(tarball, args.signing_key)
        sig_fpr = ed25519_pub_fingerprint(args.signing_key)
        print(f"[OK] Signing key fingerprint: {sig_fpr}")
    else:
        print("[WARN] No signing key supplied - publishing UNSIGNED")

    installer_name = f"deploy_update_v{version.replace('.', '_')}.php"
    installer_php = (INSTALLER_TEMPLATE
                     .replace("__VERSION__", version)
                     .replace("__CHECKSUM__", checksum)
                     .replace("__DESCRIPTION__", (args.description or f"v{version}").replace("'", "\\'"))
                     .replace("__SIG_FPR__", sig_fpr))
    installer_path = args.work_dir / installer_name
    installer_path.write_text(installer_php, encoding="utf-8")

    # FTP upload tarball, (optionally) signature, and installer
    ftp = ftp_connect()
    try:
        ftp_put(ftp, tarball, tarball.name)
        if sig_path:
            ftp_put(ftp, sig_path, sig_path.name)
        ftp_put(ftp, installer_path, installer_name)
    finally:
        try: ftp.quit()
        except Exception: ftp.close()

    # Run the installer via HTTPS
    url = args.poolai_url.rstrip("/") + "/" + installer_name
    print(f"[..] Running installer: {url}")
    with urllib.request.urlopen(url, timeout=300) as resp:
        body = resp.read().decode("utf-8", errors="replace")
    print(body)
    if "Installer self-deleted" not in body:
        fatal("installer did not self-delete; manual cleanup needed")

    # Clean up local artifacts
    tarball.unlink(missing_ok=True)
    if sig_path: sig_path.unlink(missing_ok=True)
    installer_path.unlink(missing_ok=True)
    print(f"\n[DONE] v{version} published.")


if __name__ == "__main__":
    main()
