"""
One-shot helper: merge all per-component .env files in the monorepo into a single
root .env, the new source of truth. Detects conflicting values for the same key
across files (loud error, no silent overwrite).

This script is deliberately conservative:
  - It REFUSES to write the root .env if any key has different values across sources.
  - It writes the output as UTF-8 with LF line endings.
  - Values are never printed; only key names and source-file maps are echoed.

Run from anywhere in the monorepo. Output: <repo_root>/.env (overwritten if exists).
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path


# Files to merge, in order of precedence (later wins on no-conflict tie).
# Path is relative to the monorepo root.
SOURCE_ENV_FILES = [
    "brain/.env",
    "ai-assistant/php/.env",
    "web-portal/php_deploy/.env",
    "web-portal/admin_deploy/.env",
    "web-portal/poolai_deploy/.env",
]


def find_repo_root() -> Path:
    here = Path(__file__).resolve()
    for parent in (here, *here.parents):
        if (parent / ".git").exists() and (parent / "CLAUDE.md").exists():
            return parent
    raise SystemExit("Could not locate repo root (no .git+CLAUDE.md ancestor).")


def parse_env(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE lines, ignoring comments and blanks. Returns ordered dict."""
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        # Strip optional surrounding quotes (handles 'foo' and "foo")
        value = value.strip().strip("'\"")
        if not key:
            continue
        out[key] = value
    return out


# Group keys into sections for the output file. Keys not listed here go into MISC.
SECTIONS: list[tuple[str, list[str]]] = [
    ("Shared infrastructure (Hostinger MySQL)", [
        "DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASS", "DB_PASSWORD",
    ]),
    ("Shared infrastructure (Hostinger FTP/SFTP)", [
        "SFTP_HOST", "SFTP_PORT", "SFTP_USER", "SFTP_PASSWORD", "SFTP_CHUNKS_PATH",
    ]),
    ("Shared API / secrets", [
        "ANTHROPIC_API_KEY", "CLAUDE_API_KEY",
        "BOOTSTRAP_SECRET", "JWT_SECRET",
        "ALERT_EMAIL", "SMTP_FROM",
    ]),
    ("Brain-specific (analytics consumer)", [
        "API_URL", "API_KEY",
        "OUTPUT_DIR", "LOCAL_CHUNKS_DIR", "CHUNK_SIZE",
        "DELETE_AFTER_DOWNLOAD", "CLEANUP_AFTER_MERGE",
        "DEVICE_IDS",
    ]),
    ("Web-portal / AI-assistant PHP runtime config", [
        "SESSION_NAME", "SESSION_LIFETIME",
        "MAX_UPLOAD_SIZE",
        "LOGIN_MAX_ATTEMPTS", "LOGIN_LOCKOUT_TIME",
        "DEBUG_MODE",
        "FCM_SERVER_KEY",
    ]),
]


def main() -> int:
    repo_root = find_repo_root()
    print(f"repo root: {repo_root}")

    # Read every source file, recording which file each key came from.
    per_key_values: dict[str, dict[Path, str]] = defaultdict(dict)
    sources_seen: list[Path] = []
    for rel in SOURCE_ENV_FILES:
        p = repo_root / rel
        if not p.exists():
            print(f"  SKIP (not found): {rel}")
            continue
        sources_seen.append(p)
        env = parse_env(p)
        print(f"  read {rel}: {len(env)} key(s)")
        for k, v in env.items():
            per_key_values[k][p] = v

    if not sources_seen:
        print("ERROR: no source .env files found")
        return 2

    # Detect conflicts (same key, different values across files).
    conflicts: list[str] = []
    for key, by_file in per_key_values.items():
        unique_values = set(by_file.values())
        if len(unique_values) > 1:
            sources = ", ".join(p.relative_to(repo_root).as_posix() for p in by_file)
            conflicts.append(f"  {key}: differs across {sources}")
    if conflicts:
        print()
        print("CONFLICT — these keys have different values across source files:")
        for c in conflicts:
            print(c)
        print()
        print("Resolve manually (decide canonical value) before re-running.")
        return 3

    # Special-case: DB_PASSWORD vs DB_PASS — keep DB_PASS (PHP convention),
    # since the only place DB_PASSWORD appears is brain/.env.example (not used).
    if "DB_PASSWORD" in per_key_values and "DB_PASS" in per_key_values:
        print("  note: dropping DB_PASSWORD (using DB_PASS as canonical)")
        per_key_values.pop("DB_PASSWORD", None)

    # Build the consolidated file, grouping into sections.
    out = repo_root / ".env"
    lines: list[str] = []
    lines.append("# PoolAIssistant - Root environment file (single source of truth)")
    lines.append("# Generated by scripts/consolidate_env.py from per-component .env files.")
    lines.append("# This file is gitignored. NEVER commit secrets.")
    lines.append("#")
    lines.append("# Components read this via:")
    lines.append("#   - Python (brain/, scripts/): python-dotenv with find_dotenv()")
    lines.append("#     walks up from cwd to find this file")
    lines.append("#   - PHP deploy folders (web-portal/*_deploy/, ai-assistant/php/):")
    lines.append("#     KEEP their own .env at deploy time (FTP'd to server). Treat")
    lines.append("#     those as MIRRORED FROM ROOT — when rotating creds here, also")
    lines.append("#     update the deploy folders before next FTP push.")
    lines.append("")

    placed: set[str] = set()
    for section_title, keys in SECTIONS:
        section_lines = []
        for k in keys:
            if k in per_key_values:
                section_lines.append(f"{k}={list(per_key_values[k].values())[0]}")
                placed.add(k)
        if section_lines:
            lines.append(f"# --- {section_title} ---")
            lines.extend(section_lines)
            lines.append("")

    misc = sorted(set(per_key_values.keys()) - placed)
    if misc:
        lines.append("# --- Other (not categorized) ---")
        for k in misc:
            lines.append(f"{k}={list(per_key_values[k].values())[0]}")
        lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print()
    print(f"wrote {out.relative_to(repo_root)} with {len(per_key_values)} key(s)")
    print(f"  source files: {', '.join(p.relative_to(repo_root).as_posix() for p in sources_seen)}")
    print()
    print("next steps:")
    print("  1. update Python scripts to use load_dotenv(find_dotenv()) (this script doesn't do that)")
    print("  2. delete brain/.env once verified working from root")
    print("  3. leave deploy-folder .env files in place; they remain deploy artifacts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
